trigger:
- main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: ZAP_Scan
  steps:
  - script: |
      docker pull owasp/zap2docker-stable
      docker run -t owasp/zap2docker-stable zap-baseline.py -t https://example.com
    displayName: 'Run OWASP ZAP Baseline Scan'

